/* this is an autogenerated file.  edit patchlist.sh instead. */
#include "config.h"

#include <stdio.h>
#include <stdlib.h>

#include "mutt.h"

void mutt_print_patchlist (void)
{
  puts ("patch-1.5.13.cd.ifdef.2");
  puts ("patch-1.5.18.rr.compressed.1");
}
